### ARTICLE TYPES ###

### GET ALL
### Obtener todos los tipos de artículo
GET http://localhost:3000/api/articleTypes

### GET ONE
### Obtener un tipo de artículo
GET http://localhost:3000/api/articleTypes/{{idToGet}}

### POST
### Crear un nuevo tipo de artículo
POST http://localhost:3000/api/articleTypes
Content-Type: application/json

{
    "name": "Remo",
    "mainUse": "Impulsar kayak"
}

### POST 2
# @name createArticleTypeToGet
POST http://localhost:3000/api/articleTypes
Content-Type: application/json

{
    "name": "Chaleco salvavidas",
    "mainUse": "Brindar flotación y seguridad al navegante"
}

### POST 3
# @name createArticleTypeToUpdate
POST http://localhost:3000/api/articleTypes
Content-Type: application/json

{
    "name": "Carro portakayak",
    "mainUse": "Transportar el kayak fácilmente"
}

### POST 4
# @name createArticleTypeToDelete
POST http://localhost:3000/api/articleTypes
Content-Type: application/json

{
    "name": "Guantes de remo",
    "mainUse": "Proteger las manos y mejorar el agarre"
}

### UPDATE
### Modificar un tipo de artículo
PUT http://localhost:3000/api/articleTypes/{{idToUpdate}}
Content-Type: application/json

{
    "name": "Carro portakayak",
    "mainUse": "Transportar el kayak por tierra fácilmente"
}

### DELETE
### Borrar un tipo de artículo
DELETE http://localhost:3000/api/articleTypes/{{idToDelete}}

### IDs
@idToGet = {{createArticleTypeToGet.response.body.data.id}}
@idToUpdate = {{createArticleTypeToUpdate.response.body.data.id}}
@idToDelete = {{createArticleTypeToDelete.response.body.data.id}}