### obtener todos los characters
GET http://localhost:3000/api/tipoArticulo

### obtener un character
GET http://localhost:3000/api/tipoArticulo/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### crear un nuevo character
POST http://localhost:3000/api/tipoArticulo
Content-Type: application/json

{
    "id": "a02b91bc-3769-4221-beb1-d7a3aeba7dad",
    "nombre": "asv",
    "usoPrincipal": "aa"
}

### modificar un character (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/tipoArticulo/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
  "id": "a02b91bc-3769-4221-beb1-d7a3aeba7dad",
  "nombre": "Nuevo Nombre",
  "usoPrincipal": "Nuevo Uso Principal"
}

### modificar un character (PATCH - recurso parcial)
PATCH http://localhost:3000/api/tipoArticulo/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "id": "a02b91bc-3769-4221-beb1-d7a3aeba7dad",
    "nombre": "Nombre Modificado",
    "usoPrincipal": "Uso Principal Modificado"
}

### borrar un character
DELETE http://localhost:3000/api/tipoArticulo/a02b91bc-3769-4221-beb1-d7a3aeba7dad