### GET ALL 
### Obtener todos los tipos de kayak
GET http://localhost:3000/api/kayakTypes

### GET ONE
### Obtener un tipo de kayak
GET http://localhost:3000/api/kayakTypes/{{idToObtener}}


### Obtener el producto de un kayakType específico
GET http://localhost:3000/api/kayakTypes/1/product

### POST
### Crear un nuevo tipo de kayak
POST http://localhost:3000/api/kayakTypes
Content-Type: application/json

{
    "model": "Explorador",
    "brand": "Kayak Océano",
    "material": "Polietileno",
    "paddlersQuantity": 2,
    "maxWeightCapacity": 250,
    "constructionType": "Moldeado rotacional",
    "length": 4.2,
    "beam": 0.8
}

### POST 2
# @name crearKayakTypeParaObtener
POST http://localhost:3000/api/kayakTypes
Content-Type: application/json

{
    "model": "Pungo",
    "brand": "Sistemas Wilderness",
    "material": "Polietileno",
    "paddlersQuantity": 1,
    "maxWeightCapacity": 136,
    "constructionType": "Moldeado rotacional",
    "length": 3.7,
    "beam": 0.7
}

### POST 3
# @name crearKayakTypeParaActualizar
POST http://localhost:3000/api/kayakTypes
Content-Type: application/json

{
    "model": "Tempestad",
    "brand": "Sistemas Wilderness",
    "material": "Fibra de vidrio",
    "paddlersQuantity": 1,
    "maxWeightCapacity": 120,
    "constructionType": "Compuesto",
    "length": 5.2,
    "beam": 0.6
}

### POST 4
# @name crearKayakTypeParaBorrar
POST http://localhost:3000/api/kayakTypes
Content-Type: application/json

{
    "model": "Tándem",
    "brand": "Percepción",
    "material": "Polietileno",
    "paddlersQuantity": 2,
    "maxWeightCapacity": 230,
    "constructionType": "Moldeado rotacional",
    "length": 4.5,
    "beam": 0.8
}

### PUT
### Modificar un tipo de kayak
PUT http://localhost:3000/api/kayakTypes/{{idParaActualizar}}
Content-Type: application/json

{
    "model": "Tempestad Pro",
    "brand": "Sistemas Wilderness",
    "material": "Fibra de carbono",
    "paddlersQuantity": 1,
    "maxWeightCapacity": 125,
    "constructionType": "Compuesto",
    "length": 5.2,
    "beam": 0.6
}

### DELETE
### Borrar un tipo de kayak
DELETE http://localhost:3000/api/kayakTypes/{{idParaBorrar}}

### IDs
@idToObtener = {{crearKayakTypeParaObtener.response.body.data.id}}
@idParaActualizar = {{crearKayakTypeParaActualizar.response.body.data.id}}
@idParaBorrar = {{crearKayakTypeParaBorrar.response.body.data.id}}