### obtener todas las provincias
GET http://localhost:3000/api/provincia

### obtener una provincia
GET http://localhost:3000/api/provincia/3

### crear una nueva provincia
POST http://localhost:3000/api/provincia
Content-Type: application/json

{
    "codProv": "4",
    "nombreProv": "Cordoba",
    "codPais": "argentina"
}

### modificar una provincia (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/provincia/3
Content-Type: application/json

{
    "codProv": "3",
    "nombreProv": "Buenos Aires Modificado",
    "codPais": "argentina"
}

### modificar una provincia (PATCH - recurso parcial)
PATCH http://localhost:3000/api/provincia/3
Content-Type: application/json

{
    "codProv": "3",
    "nombreProv": "Nombre Modificado",
    "codPais": "Pais Modificado"
}

### borrar una provincia
DELETE http://localhost:3000/api/provincia/3