### PROVINCES ###

### GET ALL
### Obtener todas las provincias
GET http://localhost:3000/api/provinces

### GET ONE
### Obtener una provincia específica
GET http://localhost:3000/api/provinces/{{idToGet}}

### POST
### Crear una nueva provincia (Buenos Aires)
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
    "name": "Buenos Aires",
    "country": "Argentina"
}

### POST 2
# @name createProvinceToGet
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
    "name": "Córdoba",
    "country": "Argentina"
}

### POST 3
# @name createProvinceToUpdate
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
    "name": "Santa",
    "country": "Argentina"
}

### POST 4
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
    "name": "Mendoza",
    "country": "Argentina"
}


### POST 5
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
    "name": "Misiones",
    "country": "Argentina"
}

### POST 6
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
    "name": "Tucumán",
    "country": "Argentina"
}

### POST 7
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
    "name": "Salta",
    "country": "Argentina"
}

### POST 8
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
    "name": "Entre Ríos",
    "country": "Argentina"
}

### POST 9
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
    "name": "Chubut",
    "country": "Argentina"
}

### POST 10 - Provincia de Uruguay
# @name createProvinceToDelete
POST http://localhost:3000/api/provinces
Content-Type: application/json

{
    "name": "Montevideo",
    "country": "Uruguay"
}

### UPDATE
### Modificar una provincia
PUT http://localhost:3000/api/provinces/{{idToUpdate}}
Content-Type: application/json

{
    "name": "Santa Fe",
    "country": "Argentina"
}

### DELETE
### Borrar una provincia
DELETE http://localhost:3000/api/provinces/{{idToDelete}}

### IDs
@idToGet = {{createProvinceToGet.response.body.data.id}}
@idToUpdate = {{createProvinceToUpdate.response.body.data.id}}
@idToDelete = {{createProvinceToDelete.response.body.data.id}}